### ISSUE TITLE
Package paths need adjustment to import Peachy from node_modules

### ISSUE THREAD

**Issue by lostfictions** [hazzard993/peachy-types#1]
Hi, sorry to open multiple issues on your repos today. Wondering if it might be worth mentioning in this repo's README that Peachy apparently can't be imported from `node_modules` without adjustment -- it chokes when peachy tries to `require('/lib/json')`, which is vendored in the repo (and present if the repo is installed via Yarn) but not found when using the path config in your [love-typescript-template](https://github.com/hazzard993/love-typescript-template/blob/master/src/conf.ts).

Appending `";node_modules/peachy/?.lua"` seems to do the trick, but this took a bit of prodding to figure out.

**Comment by hazzard993** [comment]
Appreciate the issue being raised!

Updated the README in 0.2.0 with information about that `package.path` addition if `peachy` is within `node_modules`

**Comment by lostfictions** [comment]
Thanks a lot!
